import "~/styles/globals.css";
import "primeicons/primeicons.css";
import "primereact/resources/themes/lara-dark-teal/theme.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { PrimeReactProvider, PrimeReactContext } from "primereact/api";

import { TRPCReactProvider } from "~/trpc/react";
import TopBar from "./_components/top-bar";

export const metadata: Metadata = {
  title: "TrackIt",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <PrimeReactProvider>
            <TopBar />
            {children}
          </PrimeReactProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
